# Generated by Django 3.2.5 on 2021-09-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspartner',
            options={'ordering': ['-account']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-account']},
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='InterviewSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('schedule', models.TimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventbookings')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
