# Generated by Django 3.2.4 on 2021-07-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbookings',
            name='best_way_contact',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='eventbookings',
            name='beverages',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='eventbookings',
            name='service_requirements',
            field=models.CharField(max_length=55),
        ),
    ]
