# Generated by Django 3.2.5 on 2021-09-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210906_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewSchedules',
            new_name='InterviewSchedule',
        ),
    ]
