# Generated by Django 3.2.4 on 2021-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210630_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
