# Generated by Django 4.0.2 on 2022-04-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(default='Partially Paid', max_length=20),
        ),
    ]
