# Generated by Django 3.2.5 on 2021-09-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_interviewschedules_interviewschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='schedule',
            new_name='time',
        ),
    ]
