# Generated by Django 3.2.4 on 2021-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210630_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
