# Generated by Django 4.0.2 on 2022-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transactionlog_options_transactionlog_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionlog',
            old_name='payment',
            new_name='total_payment',
        ),
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
