# Generated by Django 3.2.5 on 2021-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_schedule_interviewschedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
