# Generated by Django 3.2.5 on 2021-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_businesspartner_services_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='services_offered',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
