# Generated by Django 3.2.4 on 2021-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210630_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='business_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='type_of_business',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
