# Generated by Django 3.2.4 on 2021-07-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210702_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='postal_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='state_province',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='EventBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_event', models.CharField(max_length=55)),
                ('venue_name', models.CharField(max_length=150)),
                ('event_budget', models.IntegerField()),
                ('desired_date', models.DateField()),
                ('time_schedule', models.TimeField()),
                ('guests_no', models.IntegerField()),
                ('service_requirements', models.CharField(max_length=10)),
                ('beverages', models.CharField(max_length=15)),
                ('best_way_contact', models.CharField(max_length=20)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
