# Generated by Django 3.2.5 on 2021-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_time_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
