# Generated by Django 3.2.5 on 2021-12-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211226_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location_name',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
    ]
