# Generated by Django 3.2.5 on 2021-12-31 01:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_client_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
