# Generated by Django 3.2.5 on 2022-01-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_client_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='venue_name',
        ),
        migrations.AddField(
            model_name='event',
            name='venue_lat',
            field=models.IntegerField(default=7.45),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_long',
            field=models.IntegerField(default=125.8),
        ),
    ]
