# Generated by Django 3.2.5 on 2022-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220117_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_lat',
            field=models.DecimalField(decimal_places=10, default=7.448212, max_digits=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_long',
            field=models.DecimalField(decimal_places=10, default=125.809425, max_digits=30),
        ),
    ]
