# Generated by Django 3.2.5 on 2022-01-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220120_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookings',
            name='best_way_contact',
        ),
        migrations.RemoveField(
            model_name='eventbookings',
            name='beverages',
        ),
        migrations.RemoveField(
            model_name='eventbookings',
            name='service_requirements',
        ),
        migrations.AddField(
            model_name='eventbookings',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbookings',
            name='event_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
