# Generated by Django 3.2.5 on 2022-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_eventbookings_time_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
