# Generated by Django 3.2.5 on 2022-01-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_interviewschedule_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbookings',
            options={'ordering': ['desired_date']},
        ),
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='AffiliationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businesspartner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
