# Generated by Django 3.2.5 on 2022-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220125_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliationrequest',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=10),
        ),
    ]
