# Generated by Django 3.2.5 on 2022-01-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_affiliationrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='affiliationrequest',
            name='task_status',
            field=models.CharField(blank='True', default='On Going', max_length=20),
        ),
    ]
