# Generated by Django 3.2.5 on 2022-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220127_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('venue_rate', models.IntegerField()),
                ('catering_rate', models.IntegerField()),
                ('styling_rate', models.IntegerField()),
                ('mc_rate', models.IntegerField()),
                ('presentation_rate', models.IntegerField()),
                ('courtesy_rate', models.IntegerField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
