# Generated by Django 4.0.2 on 2022-02-13 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 1, 43, 25, 118988, tzinfo=utc)),
        ),
    ]
