# Generated by Django 4.0.2 on 2022-03-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_businesspartner_permit_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=150)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatroom')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientroom',
            name='client',
        ),
        migrations.RemoveField(
            model_name='partnergrouproom',
            name='group_room',
        ),
        migrations.RemoveField(
            model_name='partnergrouproom',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnerroom',
            name='partner',
        ),
        migrations.DeleteModel(
            name='ClientGroupRoom',
        ),
        migrations.DeleteModel(
            name='ClientRoom',
        ),
        migrations.DeleteModel(
            name='GroupRoom',
        ),
        migrations.DeleteModel(
            name='PartnerGroupRoom',
        ),
        migrations.DeleteModel(
            name='PartnerRoom',
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatroom'),
        ),
    ]
