# Generated by Django 4.0.2 on 2022-04-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_chat_chatroom_roommember_remove_clientroom_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
