# Generated by Django 4.0.2 on 2022-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_chat_user_chat_sender_name_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
